In [1]:
import cv2
import numpy as np

In [2]:
# 1. 캔버스 생성 및 기본 정보 출력
canvas = np.zeros((500, 800, 3), dtype=np.uint8)
print(f"OpenCV 버전: {cv2.__version__}")

OpenCV 버전: 4.13.0


In [3]:
# 2. 다양한 도형 그리기 (그리기 도구 테스트)
# 선 (Blue), 사각형 (Red), 원 (Yellow)
cv2.line(canvas, (50, 50), (250, 50), (255, 0, 0), 3)
cv2.rectangle(canvas, (50, 100), (250, 250), (0, 0, 255), -1) # -1은 채우기
cv2.circle(canvas, (150, 350), 70, (0, 255, 255), 5)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(500, 800, 3), dtype=uint8)

In [4]:
# 3. 이미지 조작: 그라데이션 영역 생성
# 우측 영역에 수평 그라데이션 채우기
for i in range(400):
    canvas[:, 400 + i] = (i // 2, 0, 255 - (i // 2))

In [5]:
# 4. 이미지 프로세싱 테스트: 블러(Blur) 및 엣지(Edge) 검출
# 텍스트가 포함된 영역을 만들고 필터 적용
text_area = np.zeros((100, 400, 3), dtype=np.uint8)
cv2.putText(text_area, "Processing...", (20, 60), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 2, (255, 255, 255), 2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(100, 400, 3), dtype=uint8)

In [6]:
# 가우시안 블러 적용 (부드럽게)
blurred_text = cv2.GaussianBlur(text_area, (15, 15), 0)

In [7]:
# Canny 엣지 검출 (외곽선 따기) - 결과는 흑백(1채널)이므로 3채널로 변환하여 합성
edges = cv2.Canny(text_area, 100, 200)
edges_bgr = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)

In [8]:
# 메인 캔버스에 결과물 붙이기 (슬라이싱 사용)
canvas[50:150, 350:750] = blurred_text
canvas[200:300, 350:750] = edges_bgr

In [9]:
# 5. 최종 결과 출력
cv2.putText(canvas, "1. Shapes", (50, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 1)
cv2.putText(canvas, "2. Blur & Edge", (350, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 1)
cv2.putText(canvas, "3. Gradient", (600, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 1)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [198,   0,  57],
        [199,   0,  56],
        [199,   0,  56]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [198,   0,  57],
        [199,   0,  56],
        [199,   0,  56]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [198,   0,  57],
        [199,   0,  56],
        [199,   0,  56]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [198,   0,  57],
        [199,   0,  56],
        [199,   0,  56]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [198,   0,  57],
        [199,   0,  56],
        [199,   0,  56]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [198,   0,  57],
        [199,   0,  56],
        [199,   0,  56]]

In [10]:
cv2.imshow("Advanced OpenCV Test", canvas)
print("창을 클릭한 후 아무 키나 누르면 종료됩니다.")
cv2.waitKey(0)
cv2.destroyAllWindows()

창을 클릭한 후 아무 키나 누르면 종료됩니다.
